<?php
// Datingtips - sex55.net
$datingtips = array(

    "datingtips" => array(
        'name' => "Datingtips",
        'title' => "Datingtips - Praktisch en persoonlijk via sex55.net",
        'info' => "Handige datingtips voor 50-plussers die online nieuwe mensen willen ontmoeten. Discreet, persoonlijk en vol levenservaring via sex55.net.",
        'tekst' => "<h2>Datingtips voor Datingtips op sex55.net</h2><p>Daten na je 50e is anders dan vroeger – en dat is precies waarom het zo waardevol is. Op sex55.net draait het om mensen die weten wat ze willen: gezelschap, oprechte aandacht en fijne gesprekken. Met deze praktische datingtips helpen we je om met vertrouwen en plezier je eerste stappen te zetten of opnieuw te beginnen.</p><h3>1. Vul je profiel eerlijk en persoonlijk in</h3><p>Een goed ingevuld profiel maakt echt het verschil. Vertel iets over jezelf, je interesses en wat je zoekt. Laat je foto's recent en vriendelijk zijn – zo trek je mensen aan die bij je passen.</p><h3>2. Begin met een open en respectvol bericht</h3><p>Je hoeft geen dichter te zijn – een vriendelijke groet met een persoonlijke opmerking over haar/zijn profiel is vaak al genoeg om het ijs te breken.</p><h3>3. Wees duidelijk over je intenties</h3><p>Wil je iemand leren kennen voor een kop koffie, een wandeling of misschien een relatie? Wees eerlijk – het helpt je sneller iemand te vinden die hetzelfde wil.</p><h3>4. Neem de tijd</h3><p>Bij sex55.net hoef je niets te overhaasten. Neem rustig de tijd om iemand te leren kennen en laat het contact op een natuurlijke manier groeien.</p><p>Met deze tips ga je goed voorbereid en zelfverzekerd op zoek naar fijne nieuwe ontmoetingen. Veel plezier – en wie weet wat er op je pad komt!</p>"
    ),

    "nl" => array(
        'name' => "Datingtips Nederland",
        'title' => "Datingtips Nederland - Praktisch en persoonlijk via sex55.net",
        'info' => "Ontdek datingtips speciaal voor 50+ singles in Nederland. Voor gezelschap, nieuwe ontmoetingen of serieuze relaties via sex55.net.",
        'tekst' => "<h2>Datingtips voor Nederland op sex55.net</h2><p>Daten na je 50e is anders dan vroeger – en dat is precies waarom het zo waardevol is. Op sex55.net draait het om mensen die weten wat ze willen: gezelschap, oprechte aandacht en fijne gesprekken. Met deze praktische datingtips helpen we je om met vertrouwen en plezier je eerste stappen te zetten of opnieuw te beginnen.</p><h3>1. Vul je profiel eerlijk en persoonlijk in</h3><p>Een goed ingevuld profiel maakt echt het verschil. Vertel iets over jezelf, je interesses en wat je zoekt. Laat je foto's recent en vriendelijk zijn – zo trek je mensen aan die bij je passen.</p><h3>2. Begin met een open en respectvol bericht</h3><p>Je hoeft geen dichter te zijn – een vriendelijke groet met een persoonlijke opmerking over haar/zijn profiel is vaak al genoeg om het ijs te breken.</p><h3>3. Wees duidelijk over je intenties</h3><p>Wil je iemand leren kennen voor een kop koffie, een wandeling of misschien een relatie? Wees eerlijk – het helpt je sneller iemand te vinden die hetzelfde wil.</p><h3>4. Neem de tijd</h3><p>Bij sex55.net hoef je niets te overhaasten. Neem rustig de tijd om iemand te leren kennen en laat het contact op een natuurlijke manier groeien.</p><p>Met deze tips ga je goed voorbereid en zelfverzekerd op zoek naar fijne nieuwe ontmoetingen. Veel plezier – en wie weet wat er op je pad komt!</p>"
    ),

    "be" => array(
        'name' => "Datingtips België",
        'title' => "Datingtips België - Praktisch en persoonlijk via sex55.net",
        'info' => "Ontdek datingtips speciaal voor 50+ singles in België. Voor gezelschap, nieuwe ontmoetingen of serieuze relaties via sex55.net.",
        'tekst' => "<h2>Datingtips voor België op sex55.net</h2><p>Daten na je 50e is anders dan vroeger – en dat is precies waarom het zo waardevol is. Op sex55.net draait het om mensen die weten wat ze willen: gezelschap, oprechte aandacht en fijne gesprekken. Met deze praktische datingtips helpen we je om met vertrouwen en plezier je eerste stappen te zetten of opnieuw te beginnen.</p><h3>1. Vul je profiel eerlijk en persoonlijk in</h3><p>Een goed ingevuld profiel maakt echt het verschil. Vertel iets over jezelf, je interesses en wat je zoekt. Laat je foto's recent en vriendelijk zijn – zo trek je mensen aan die bij je passen.</p><h3>2. Begin met een open en respectvol bericht</h3><p>Je hoeft geen dichter te zijn – een vriendelijke groet met een persoonlijke opmerking over haar/zijn profiel is vaak al genoeg om het ijs te breken.</p><h3>3. Wees duidelijk over je intenties</h3><p>Wil je iemand leren kennen voor een kop koffie, een wandeling of misschien een relatie? Wees eerlijk – het helpt je sneller iemand te vinden die hetzelfde wil.</p><h3>4. Neem de tijd</h3><p>Bij sex55.net hoef je niets te overhaasten. Neem rustig de tijd om iemand te leren kennen en laat het contact op een natuurlijke manier groeien.</p><p>Met deze tips ga je goed voorbereid en zelfverzekerd op zoek naar fijne nieuwe ontmoetingen. Veel plezier – en wie weet wat er op je pad komt!</p>"
    ),

    "de" => array(
        'name' => "Datingtips Duitsland",
        'title' => "Datingtips Duitsland - Praktisch en persoonlijk via sex55.net",
        'info' => "Ontdek datingtips speciaal voor 50+ singles in Duitsland. Voor gezelschap, nieuwe ontmoetingen of serieuze relaties via sex55.net.",
        'tekst' => "<h2>Datingtips voor Duitsland op sex55.net</h2><p>Daten na je 50e is anders dan vroeger – en dat is precies waarom het zo waardevol is. Op sex55.net draait het om mensen die weten wat ze willen: gezelschap, oprechte aandacht en fijne gesprekken. Met deze praktische datingtips helpen we je om met vertrouwen en plezier je eerste stappen te zetten of opnieuw te beginnen.</p><h3>1. Vul je profiel eerlijk en persoonlijk in</h3><p>Een goed ingevuld profiel maakt echt het verschil. Vertel iets over jezelf, je interesses en wat je zoekt. Laat je foto's recent en vriendelijk zijn – zo trek je mensen aan die bij je passen.</p><h3>2. Begin met een open en respectvol bericht</h3><p>Je hoeft geen dichter te zijn – een vriendelijke groet met een persoonlijke opmerking over haar/zijn profiel is vaak al genoeg om het ijs te breken.</p><h3>3. Wees duidelijk over je intenties</h3><p>Wil je iemand leren kennen voor een kop koffie, een wandeling of misschien een relatie? Wees eerlijk – het helpt je sneller iemand te vinden die hetzelfde wil.</p><h3>4. Neem de tijd</h3><p>Bij sex55.net hoef je niets te overhaasten. Neem rustig de tijd om iemand te leren kennen en laat het contact op een natuurlijke manier groeien.</p><p>Met deze tips ga je goed voorbereid en zelfverzekerd op zoek naar fijne nieuwe ontmoetingen. Veel plezier – en wie weet wat er op je pad komt!</p>"
    ),

    "uk" => array(
        'name' => "Datingtips Verenigd Koninkrijk",
        'title' => "Datingtips Verenigd Koninkrijk - Praktisch en persoonlijk via sex55.net",
        'info' => "Ontdek datingtips speciaal voor 50+ singles in Verenigd Koninkrijk. Voor gezelschap, nieuwe ontmoetingen of serieuze relaties via sex55.net.",
        'tekst' => "<h2>Datingtips voor Verenigd Koninkrijk op sex55.net</h2><p>Daten na je 50e is anders dan vroeger – en dat is precies waarom het zo waardevol is. Op sex55.net draait het om mensen die weten wat ze willen: gezelschap, oprechte aandacht en fijne gesprekken. Met deze praktische datingtips helpen we je om met vertrouwen en plezier je eerste stappen te zetten of opnieuw te beginnen.</p><h3>1. Vul je profiel eerlijk en persoonlijk in</h3><p>Een goed ingevuld profiel maakt echt het verschil. Vertel iets over jezelf, je interesses en wat je zoekt. Laat je foto's recent en vriendelijk zijn – zo trek je mensen aan die bij je passen.</p><h3>2. Begin met een open en respectvol bericht</h3><p>Je hoeft geen dichter te zijn – een vriendelijke groet met een persoonlijke opmerking over haar/zijn profiel is vaak al genoeg om het ijs te breken.</p><h3>3. Wees duidelijk over je intenties</h3><p>Wil je iemand leren kennen voor een kop koffie, een wandeling of misschien een relatie? Wees eerlijk – het helpt je sneller iemand te vinden die hetzelfde wil.</p><h3>4. Neem de tijd</h3><p>Bij sex55.net hoef je niets te overhaasten. Neem rustig de tijd om iemand te leren kennen en laat het contact op een natuurlijke manier groeien.</p><p>Met deze tips ga je goed voorbereid en zelfverzekerd op zoek naar fijne nieuwe ontmoetingen. Veel plezier – en wie weet wat er op je pad komt!</p>"
    ),

    "at" => array(
        'name' => "Datingtips Oostenrijk",
        'title' => "Datingtips Oostenrijk - Praktisch en persoonlijk via sex55.net",
        'info' => "Ontdek datingtips speciaal voor 50+ singles in Oostenrijk. Voor gezelschap, nieuwe ontmoetingen of serieuze relaties via sex55.net.",
        'tekst' => "<h2>Datingtips voor Oostenrijk op sex55.net</h2><p>Daten na je 50e is anders dan vroeger – en dat is precies waarom het zo waardevol is. Op sex55.net draait het om mensen die weten wat ze willen: gezelschap, oprechte aandacht en fijne gesprekken. Met deze praktische datingtips helpen we je om met vertrouwen en plezier je eerste stappen te zetten of opnieuw te beginnen.</p><h3>1. Vul je profiel eerlijk en persoonlijk in</h3><p>Een goed ingevuld profiel maakt echt het verschil. Vertel iets over jezelf, je interesses en wat je zoekt. Laat je foto's recent en vriendelijk zijn – zo trek je mensen aan die bij je passen.</p><h3>2. Begin met een open en respectvol bericht</h3><p>Je hoeft geen dichter te zijn – een vriendelijke groet met een persoonlijke opmerking over haar/zijn profiel is vaak al genoeg om het ijs te breken.</p><h3>3. Wees duidelijk over je intenties</h3><p>Wil je iemand leren kennen voor een kop koffie, een wandeling of misschien een relatie? Wees eerlijk – het helpt je sneller iemand te vinden die hetzelfde wil.</p><h3>4. Neem de tijd</h3><p>Bij sex55.net hoef je niets te overhaasten. Neem rustig de tijd om iemand te leren kennen en laat het contact op een natuurlijke manier groeien.</p><p>Met deze tips ga je goed voorbereid en zelfverzekerd op zoek naar fijne nieuwe ontmoetingen. Veel plezier – en wie weet wat er op je pad komt!</p>"
    ),

    "ch" => array(
        'name' => "Datingtips Zwitserland",
        'title' => "Datingtips Zwitserland - Praktisch en persoonlijk via sex55.net",
        'info' => "Ontdek datingtips speciaal voor 50+ singles in Zwitserland. Voor gezelschap, nieuwe ontmoetingen of serieuze relaties via sex55.net.",
        'tekst' => "<h2>Datingtips voor Zwitserland op sex55.net</h2><p>Daten na je 50e is anders dan vroeger – en dat is precies waarom het zo waardevol is. Op sex55.net draait het om mensen die weten wat ze willen: gezelschap, oprechte aandacht en fijne gesprekken. Met deze praktische datingtips helpen we je om met vertrouwen en plezier je eerste stappen te zetten of opnieuw te beginnen.</p><h3>1. Vul je profiel eerlijk en persoonlijk in</h3><p>Een goed ingevuld profiel maakt echt het verschil. Vertel iets over jezelf, je interesses en wat je zoekt. Laat je foto's recent en vriendelijk zijn – zo trek je mensen aan die bij je passen.</p><h3>2. Begin met een open en respectvol bericht</h3><p>Je hoeft geen dichter te zijn – een vriendelijke groet met een persoonlijke opmerking over haar/zijn profiel is vaak al genoeg om het ijs te breken.</p><h3>3. Wees duidelijk over je intenties</h3><p>Wil je iemand leren kennen voor een kop koffie, een wandeling of misschien een relatie? Wees eerlijk – het helpt je sneller iemand te vinden die hetzelfde wil.</p><h3>4. Neem de tijd</h3><p>Bij sex55.net hoef je niets te overhaasten. Neem rustig de tijd om iemand te leren kennen en laat het contact op een natuurlijke manier groeien.</p><p>Met deze tips ga je goed voorbereid en zelfverzekerd op zoek naar fijne nieuwe ontmoetingen. Veel plezier – en wie weet wat er op je pad komt!</p>"
    ),

);
